version: '3.8'

services:
  app:
    build: .
    container_name: tipbot
    volumes:
      - ./:/home/devUser/dev/tip-bot
    ports:
      - 5000:5000
    env_file:
      - ./.env
    links:
      - postgres
    depends_on:
      - postgres
    stdin_open: true
    tty: true 

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
